### ISSUE TITLE
Can it be used with Bolt?

### ISSUE THREAD

**Issue by RomanZhu** [lazlo-bonin/gocs#3]
Hi

Friend of mine is using only Bolt for his games, so I was thinking about ways he can add some logic to the game using it, while I will do lower level stuff
Is it possible to create components/systems using Bolt? I'm not familiar with it, but I don't see a way to inherit classes there

What workflow would you suggest?

**Comment by lazlo-bonin** [comment]
Hi Roman,

The short answer is no. The long answer is that GoCS is entirely unrelated to Bolt, and in Bolt 1 I don't see a way of implementing a similar pattern, because the language doesn't have classes. In Bolt 2, there will be classes, which should allow to implement something akin to GoCS, albeit without the interface inheritance (the components would all be concrete). There would also need to be a query helper written for Bolt classes.
